<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Live Stock Map</title>

    <!--Bootrtap v5.2.0-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>

    <!--CSS File-->
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!--Font-->
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">

    <!-- BoxIcons v2.1.2 -->
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

   <!-- JS File -->
   <script type="text/javascript" src="script.js"defer></script>
  
</head>
<body>
 
    <!--Student Details -->
<nav>
    <div class="nav-brand">
        <img src="images/logo.jpg" alt="...">
        <div class="info">
            <h2>ISU San Mateo</h2>
            <p>Students</p>
        </div>
    </div>
    
    <ul class="nav-list-top" >
        <li class="nav-item">
            <span>Edward Balot</span>
        </li>
        <li class="nav-item">
            <span>Ariel Jacob</span>
        </li>
		<br>
		<li class="nav-item">
            <a href="log/index.php"><span>I'm an Editor!</span></a>
        </li>
    </ul>


        
</nav>
<a href="#sanmateoisab">
    <button class="san">
        San Mateo Isabela Live Stock Map
    </button>
</a>

<!--Map Details-->

<ol class="mapDetails" type="1">

    <li>
         <span>Bagong Sikat</span>
    </li>
    <li>
        <span>Marasat Pequeño</span>
    </li>
    <li>
        <span>San Antonio</span>
    </li>
    <li>
        <span>San Andres</span>
    </li>
    <li>
        <span>San Roque</span>
    </li>
    <li>
        <span>Daramuangan Norte</span>
    </li>
    <li>
        <span>Villa Gamiao</span>
    </li>
    <li>
        <span>San Ignacio</span>
    </li>
    <li>
        <span>Gaddanan</span>
    </li>
    <li>
        <span>Mapuroc</span>
    </li>
    <li>
        <span>Salinungan East</span>
    </li>
    <li>
        <span>Daramuangan Sur</span>
    </li>
    <li>
        <span>Marasat Grande</span>
    </li>
    <li>
        <span>Old Centro II</span>
    </li>
    <li>
        <span>Bacareña</span>
    </li>
    <li>
        <span>Barangay II</span>
    </li>
    <li>
        <span>Barangay IV</span>
    </li>
    <li>
        <span>Barangay I</span>
    </li>
    <li>
        <span>Old Centro I</span>
    </li>
    <li >
        <span>Malasin</span>
    </li>
    <li >
        <span>Salinungan West</span>
    </li>
    <li >
        <span>Barangay III</span>
    </li>
    <li >
        <span>Estrella</span>
    </li>
    <li >
        <span>Dagupan</span>
    </li>
    <li >
        <span>Bella Luz</span>
    </li>
    <li >
        <span>San Manuel</span>
    </li>
    <li >
        <span>Victoria</span>
    </li>
    <li >
        <span>Sinamar Norte</span>
    </li>
    <li >
        <span>Villa Magat</span>
    </li>
    <li >
        <span>Sinamar Sur</span>
    </li>
    <li >
        <span>Villa Cruz</span>
    </li>
    <li >
        <span>Villafuerte</span>
    </li>
    <li >
        <span>San Marcos</span>
    </li>
    </ol>

<!-- Image Map Generated by http://www.image-map.net/ -->
<div class="container">
 
    <div class="products-container">

        
           

<img src="images/map.png" usemap="#image-map" id="sanmateo">

<map name="image-map">
    <area target="_self" alt="Bagong Sikat" title="Bagong Sikat" href="#bagongsikat" coords="193,39,288,17,293,24,300,52,263,70,245,82,235,84,216,97,207,107,199,97,195,61" shape="poly">
    <area target="_self" alt="Marasat Pequeno" title="Marasat Pequeno" href="#pequeno" coords="299,53,262,71,282,131,299,115,313,151,321,150,293,83,309,76" shape="poly">
    <area target="_self" alt="San Antonio" title="San Antonio" href="#sanantonio" coords="297,82,322,151,329,151,322,105,310,78" shape="poly">
    <area target="_self" alt="San Andres" title="San Andres" href="#sanandres" coords="266,91,241,96,248,119,238,138,281,131" shape="poly">
    <area target="_self" alt="San Roque" title="San Roque" href="#sanroque" coords="209,108,207,138,196,158,209,163,220,165,220,173,227,172,241,164,246,157,259,154,261,138,238,137,248,115,238,99,268,90,263,72,236,86,217,98" shape="poly">
    <area target="_self" alt="Daramuangan Norte" title="Daramuangan Norte" href="#darnorte" coords="299,118,283,133,284,171,303,194,314,178,311,170,318,170,312,163,319,163,321,153,312,150" shape="poly">
    <area target="_self" alt="Villa Gamiao" title="Villa Gamiao" href="#villagamiao" coords="326,151,359,155,354,181,347,180,341,182,338,175,329,179,316,176" shape="poly">
    <area target="_self" alt="San Ignacio" title="San Ignacio" href="#sanignacio" coords="281,132,264,138,261,156,249,158,243,166,229,175,220,176,212,195,225,198,238,200,235,211,244,211,245,188,250,191,253,178,260,172,267,173,283,170" shape="poly">
    <area target="_self" alt="Gaddanan" title="Gaddanan" href="#gaddanan" coords="361,157,464,176,426,207,416,196,407,200,391,195,379,199,379,190,359,179" shape="poly">
    <area target="_self" alt="Mapuroc" title="Mapuroc" href="#mapuroc" coords="196,161,208,166,221,164,212,195,234,201,204,202,195,201,190,203,183,203,171,201,176,177" shape="poly">
    <area target="_self" alt="Salinungan East" title="Salinungan East" href="#salinunganeast" coords="318,175,311,181,330,201,337,198,347,198,368,199,376,207,379,189,358,179,350,179,339,183,338,176,328,179" shape="poly">
    <area target="_self" alt="Daramuangan Sur" title="Daramuangan Sur" href="#darsur" coords="267,175,283,172,301,194,277,211,267,211" shape="poly">
    <area target="_self" alt="Marasat Grande" title="Marasat Grande" href="#grande" coords="267,175,264,212,234,218,204,218,206,211,199,210,182,207,195,201,204,202,220,201,234,201,236,210,245,210,246,191,252,191,255,177" shape="poly">
    <area target="_self" alt="Old Centro II" title="Old Centro II" href="#oldcentroii" coords="167,201,194,214,191,228,175,225,169,228,148,222,151,215" shape="poly">
    <area target="_self" alt="Bacarena" title="Bacarena" href="#bacarena" coords="197,212,192,231,204,234,205,217" shape="poly">
    <area target="_self" alt="Barangay II" title="Barangay II" href="#barangayii" coords="242,219,225,219,221,257,221,257,234,257,233,257,234,257" shape="poly">
    <area target="_self" alt="Barangay IV" title="Barangay IV" href="#barangayiv" coords="243,219,235,258,241,266,250,269,263,225,274,222,276,214" shape="poly">
    <area target="_self" alt="Barangay I" title="Barangay I" href="#barangayi" coords="223,220,221,255,215,259,212,267,195,267,195,260,203,256,205,236,208,219" shape="poly">
    <area target="_self" alt="Old Centro I" title="Old Centro I" href="#oldcentroi" coords="146,223,128,231,121,247,130,259,151,265,156,273,162,275,179,269,186,270,193,266,195,258,203,256,206,242,203,236,191,233,189,227,176,225,171,228" shape="poly">
    <area target="_self" alt="Malasin" title="Malasin" href="#malasin" coords="313,181,328,206,332,218,322,223,327,237,320,233,309,241,314,250,308,262,317,275,306,281,302,288,300,299,292,305,280,318,266,319,260,320,261,305,285,301,289,283,253,270,264,226,279,221,277,213,304,197" shape="poly">
    <area target="_self" alt="Salinungan West" title="Salinungan West" href="#salinunganwest" coords="425,208,394,235,357,305,327,337,312,323,313,316,301,314,297,303,303,297,303,284,317,276,310,264,316,251,311,243,319,238,329,236,326,221,334,217,330,202,338,200,346,199,366,199,371,204,377,206,377,200,389,197,404,201,416,201" shape="poly">
    <area target="_self" alt="Barangay III" title="Barangay III" href="#barangayiii" coords="218,258,216,267,231,269,235,260" shape="poly">
    <area target="_self" alt="Estrella" title="Estrella" href="#estrella" coords="130,259,113,266,103,275,160,305,176,305,188,300,189,290,182,288,178,271,165,276,157,274,151,267" shape="poly">
    <area target="_self" alt="Dagupan" title="Dagupan" href="#dagupan" coords="191,269,181,272,185,287,187,303,170,314,202,318,201,308,215,307,218,296,234,292,238,287,244,285,249,270,238,268" shape="poly">
    <area target="_self" alt="Bella Luz" title="Bella Luz" href="#bellaluz" coords="102,276,96,285,77,292,70,304,69,310,65,313,72,320,82,318,90,330,99,325,104,332,118,333,116,339,125,339,141,331,147,326,162,325,176,307,161,304" shape="poly">
    <area target="_self" alt="San Manuel" title="San Manuel" href="#sanmanuel" coords="252,271,286,284,285,297,260,302,256,329,235,343,217,345,192,331,186,335,167,325,169,317,199,318,203,308,213,307,219,296,237,293,239,285,245,286" shape="poly">
    <area target="_self" alt="Victoria" title="Victoria" href="#victoria" coords="326,337,281,383,281,370,277,360,275,350,274,343,278,334,269,334,267,321,280,320,288,310,296,303,299,313,310,313,314,323" shape="poly">
    <area target="_self" alt="Sinamar Norte" title="Sinamar Norte" href="#sinamarnorte" coords="64,314,51,315,38,320,30,325,19,333,25,345,32,342,44,346,60,352,64,358,71,360,78,359,92,368,104,367,104,375,111,374,115,369,128,380,141,372,144,359,127,343,117,341,118,335,111,337,103,334,99,327,92,331,86,326,82,318" shape="poly">
    <area target="_self" alt="Villa Magat" title="Villa Magat" href="#villamagat" coords="130,342,144,359,144,371,155,366,173,364,180,365,185,370,191,370,197,368,204,354,215,348,212,341,198,336,193,333,188,334,176,332,164,326,152,327,143,331,134,337" shape="poly">
    <area target="_self" alt="Sinamar Sur" title="Sinamar Sur" href="#sinamarsur" coords="27,348,60,390,67,385,79,386,83,396,94,394,103,388,116,384,127,381,116,370,114,376,102,375,104,368,93,367,81,359,75,360,62,357,57,347,34,344" shape="poly">
    <area target="_self" alt="Villa Cruz" title="Villa Cruz" href="#villacruz" coords="266,322,260,323,256,332,237,344,215,349,216,363,237,362,240,409,227,412,227,442,259,409,282,385,282,368,277,362,275,348,277,335,268,331" shape="poly">
    <area target="_self" alt="Villafuerte" title="Villafuerte" href="#villafuerte" coords="240,408,151,410,115,386,149,368,169,364,179,364,185,369,200,369,205,355,214,350,215,359,238,363" shape="poly">
    <area target="_self" alt="San Marcos" title="San Marcos" href="#sanmarcos" coords="148,408,71,408,61,394,69,386,78,387,81,394,96,393,117,386" shape="poly">
</map>






<!--THESE IS THE EDITABLE PART WHERE DETAILS OF EVERY BARANGAY CAN BE EDITED-->

<!--Bagong Sikat-->
<div class="popup" id="bagongsikat">
    
    <br>
    <a href="#" class="close"></a>
    <h2>Bagong Sikat</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		
				<?php
					include('admin/1/conn.php');
					$query=mysqli_query($conn,"select * from `user`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						
						</tr>
						<?php
					}
				?>
			</tbody>
            <div>
			    </div>		
		</table>
        
	</div>





</div>
<!--Marasat Pequeno-->
<div class="popup" id="pequeno">
    
    <br>
    <a href="#" class="close"></a>
    <h2>Marasat Pequeno</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/2/conn.php');
					$query=mysqli_query($conn,"select * from `user2`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>




    </div>
<!--San Antonio-->
<div class="popup" id="sanantonio">
    
    <br>
    <a href="#" class="close"></a>
    <h2>San Antonio</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/3/conn.php');
					$query=mysqli_query($conn,"select * from `user3`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
							
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>



    </div>

<!--San Andres-->
<div class="popup" id="sanandres">
    
    <br>
    <a href="#" class="close"></a>
    <h2>San Andres</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/4/conn.php');
					$query=mysqli_query($conn,"select * from `user4`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>




    </div>    
<!--San Roque-->
<div class="popup" id="sanroque">
    
    <br>
    <a href="#" class="close"></a>
    <h2>San Roque</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/5/conn.php');
					$query=mysqli_query($conn,"select * from `user5`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>


    </div>    
<!--Daramuangan Norte-->
<div class="popup" id="darnorte">
    
    <br>
    <a href="#" class="close"></a>
    <h2>Daramuangan Norte</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin6/conn.php');
					$query=mysqli_query($conn,"select * from `user6`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>




    </div>    
<!--Villa Gamiao-->
<div class="popup" id="villagamiao">
    
    <br>
    <a href="#" class="close"></a>
    <h2>Villa Gamiao</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/7/conn.php');
					$query=mysqli_query($conn,"select * from `user7`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>


    </div>    
<!--San Ignacio-->
<div class="popup" id="sanignacio">
    
    <br>
    <a href="#" class="close"></a>
    <h2>San Ignacio</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/8/conn.php');
					$query=mysqli_query($conn,"select * from `user8`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>



    </div>    
<!--Gaddanan-->
<div class="popup" id="gaddanan">
    
    <br>
    <a href="#" class="close"></a>
    <h2>Gaddanan</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/9/conn.php');
					$query=mysqli_query($conn,"select * from `user9`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>



    </div>    
<!--Mapuroc-->
<div class="popup" id="mapuroc">
  
    <br>
    <a href="#" class="close"></a>
    <h2>Mapuroc</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/10/conn.php');
					$query=mysqli_query($conn,"select * from `user10`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>
    
    </div>    
<!--Salinungan East-->
<div class="popup" id="salinunganeast">

    <br>
    <a href="#" class="close"></a>
    <h2>Salinungan East</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/11/conn.php');
					$query=mysqli_query($conn,"select * from `user11`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>

    </div>    
<!--Daramuangan Sur-->
<div class="popup" id="darsur">
   
    <br>
    <a href="#" class="close"></a>
    <h2>Daramuangan Sur</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/12/conn.php');
					$query=mysqli_query($conn,"select * from `user12`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>

    </div>    
<!--Marasat Grande-->
<div class="popup" id="grande">
    
    <br>
    <a href="#" class="close"></a>
    <h2>Marasat Grande</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/13/conn.php');
					$query=mysqli_query($conn,"select * from `user13`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>
    
    
    </div>    
<!--Old Centro II-->
<div class="popup" id="oldcentroii">
    
    <br>
    <a href="#" class="close"></a>
    <h2>Old Centro II</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/14/conn.php');
					$query=mysqli_query($conn,"select * from `user14`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>

    </div>    
<!--Bacarena-->
<div class="popup" id="bacarena">
   
    <br>
    <a href="#" class="close"></a>
    <h2>Bacarena</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/15/conn.php');
					$query=mysqli_query($conn,"select * from `user15`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
       
	</div>

    </div>    
<!--Barangay II-->
<div class="popup" id="barangayii">
    
    <br>
    <a href="#" class="close"></a>
    <h2>Barangay II</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/16/conn.php');
					$query=mysqli_query($conn,"select * from `user16`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>


</div>
<!--Barangay IV-->
<div class="popup" id="barangayiv">
   
    <br>
    <a href="#" class="close"></a>
    <h2>Barangay IV</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/17/conn.php');
					$query=mysqli_query($conn,"select * from `user17`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>

    </div>    
<!--Barangay I-->
<div class="popup" id="barangayi">
   
    <br>
    <a href="#" class="close"></a>
    <h2>Barangay I</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/18/conn.php');
					$query=mysqli_query($conn,"select * from `user18`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>



    </div>    
<!--Old Centro I-->
<div class="popup" id="oldcentroi">
   
    <br>
    <a href="#" class="close"></a>
    <h2>Old Centro I</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/19/conn.php');
					$query=mysqli_query($conn,"select * from `user19`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>


    </div>    
<!--Malasin-->
<div class="popup" id="malasin">
   
    <br>
    <a href="#" class="close"></a>
    <h2>Malasin</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/20/conn.php');
					$query=mysqli_query($conn,"select * from `user20`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>

    </div>    
<!--Salinungan West-->
<div class="popup" id="salinunganwest">
   
    <br>
    <a href="#" class="close"></a>
    <h2>Salinungan West</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/21/conn.php');
					$query=mysqli_query($conn,"select * from `user21`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>


    </div>    
<!--Barangay III-->
<div class="popup" id="barangayiii">

    <br>
    <a href="#" class="close"></a>
    <h2>Barangay III</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/22/conn.php');
					$query=mysqli_query($conn,"select * from `user22`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>
    </div>    
<!--Estrella-->
<div class="popup" id="estrella">

    <br>
    <a href="#" class="close"></a>
    <h2>Estrella</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/23/conn.php');
					$query=mysqli_query($conn,"select * from `user23`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>

    </div>    
<!--Dagupan-->
<div class="popup" id="dagupan">

    <br>
    <a href="#" class="close"></a>
    <h2>Dagupan</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/24/conn.php');
					$query=mysqli_query($conn,"select * from `user24`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>

    </div>    
<!--Bella Luz-->
<div class="popup" id="bellaluz">

    <br>
    <a href="#" class="close"></a>
    <h2>Bella Luz</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/25/conn.php');
					$query=mysqli_query($conn,"select * from `user25`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>
    </div>    
<!--San Manuel-->
<div class="popup" id="sanmanuel">

    <br>
    <a href="#" class="close"></a>
    <h2>San Manuel</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/26/conn.php');
					$query=mysqli_query($conn,"select * from `user26`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>

    </div>    
<!--Victoria-->
<div class="popup" id="victoria">

    <br>
    <a href="#" class="close"></a>
    <h2>Victoria</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/27/conn.php');
					$query=mysqli_query($conn,"select * from `user27`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>
    </div>    
<!--Sinamar Norte-->
<div class="popup" id="sinamarnorte">
   
    <br>
    <a href="#" class="close"></a>
    <h2>Sinamar Norte</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/28/conn.php');
					$query=mysqli_query($conn,"select * from `user28`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>

    </div>    
<!--Villa Magat-->
<div class="popup" id="villamagat">
   
    <br>
    <a href="#" class="close"></a>
    <h2>Villa Magat</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/29/conn.php');
					$query=mysqli_query($conn,"select * from `user29`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>

    </div>    
<!--Sinamar Sur-->
<div class="popup" id="sinamarsur">
  
    <br>
    <a href="#" class="close"></a>
    <h2>Sinamar Norte</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/30/conn.php');
					$query=mysqli_query($conn,"select * from `user30`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>

    </div>    
<!--Villa Cruz-->
<div class="popup" id="villacruz">
  
    <br>
    <a href="#" class="close"></a>
    <h2>Villa Cruz</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/31/conn.php');
					$query=mysqli_query($conn,"select * from `user31`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>

    </div>    
<!--Villafuert-->
<div class="popup" id="villafuerte">

    <br>
    <a href="#" class="close"></a>
    <h2>Villafuerte</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/32/conn.php');
					$query=mysqli_query($conn,"select * from `user32`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>

    </div>    
<!--San Marcos-->
<div class="popup" id="sanmarcos">
 
    <br>
    <a href="#" class="close"></a>
    <h2>San Marcos</h2>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/33/conn.php');
					$query=mysqli_query($conn,"select * from `user33`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>
    
    </div>    

    



    <!--San Mateo Isabela Total-->
<div class="popup" id="sanmateoisab">
  
    <br>
    <a href="#" class="close"></a>
    <h2>San Mateo</h2>
    <p>Total LiveStock</p>
    <div>
		<table border="1">
			<thead>
				<th>Livestock</th>
				<th>Male</th>
				<th>Female</th>
				<th>Total</th>
				<th>Raiser</th>
				<th></th>
			</thead>
			<tbody>
		<div>
	    </div>		
				<?php
					include('admin/34/conn.php');
					$query=mysqli_query($conn,"select * from `user34`");
					while($row=mysqli_fetch_array($query)){
						?>
						<tr>
							<td><?php echo $row['livestock']; ?></td>
							<td><?php echo $row['male']; ?></td>
							<td><?php echo $row['female']; ?></td>
							<td><?php echo $row['total']; ?></td>
							<td><?php echo $row['raiser']; ?></td>
							<td></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
        
	</div>
    </div>    


<!--END OF DETAILS-->



    
        
  
 
</body>
</html>